version: "3.8"

services:
  db:
    image: postgres:15
    container_name: leaveit-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: leaveit-app
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    command: ["dotnet", "leave-it-small.dll"]
  
  traefik: 
      image: traefik:v3.5
      command: 
        - "--api.insecure=true"
        - "--providers.docker=true"
        - "--entrypoints.web.address=:80"
      ports:
        - "80:80"
        - "8080:8080"

      volumes:
        - /var/run/docker.sock:/var/run/docker.sock

volumes:
  postgres_data:
  
