services:
  db:
    image: postgres:15
    container_name: leaveit-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: leaveit-app
    restart: always
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    command: ["dotnet", "leave-it-small.dll"]
    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.leaveit-api.rule=Host(`localhost`) &&  PathPrefix(`/api`)"
        - "traefik.http.routers.leaveit-api.entrypoints=websecure"
        - "traefik.http.routers.leaveit-api.tls.certresolver=letsencrypt"

        - "traefik.http.routers.leaveit-redirect.rule=Host(`localhost`)"
        - "traefik.http.routers.leaveit-redirect.entrypoints=websecure"
        - "traefik.http.routers.leaveit-redirect.tls.certresolver=letsencrypt"
        - "traefik.http.routers.leaveit-redirect.priority=1"
        - "traefik.http.services.leaveit-service.loadbalancer.server.port=5000" 
  
  traefik: 
      image: traefik:v3.5
      command: 
        - "--api.dashboard=true"
        - "--entrypoints.web.address=:80"
        - "--entrypoints.websecure.address=:443"
        - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
        - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
        - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
        - "--certificatesresolvers.letsencrypt.acme.email=${LE_EMAIL}"
        - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
        - "--providers.docker=true"
        - "--providers.docker.exposedbydefault=false"
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - traefik-certs:/letsencrypt

      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.traefik.rule=Host(`traefik.localhost`)"
        - "traefik.http.routers.traefik.service=api@internal"
        - "traefik.http.routers.traefik.entrypoints=websecure"
        - "traefik.http.routers.traefik.tls.certresolver=letsencrypt"
        - "traefik.http.routers.traefik.middlewares=auth@docker"
        - "traefik.http.middlewares.auth.basicauth.users=${TRAEFIK_DASHBOARD_AUTH}"       

volumes:
  postgres_data:
  traefik-certs:
  
